# Generated by Django 4.2.16 on 2024-10-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='deposit_amount',
            field=models.PositiveIntegerField(),
        ),
    ]
