# Generated by Django 4.2.16 on 2024-10-21 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0002_alter_deposit_deposit_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
