# Generated by Django 4.2.16 on 2025-05-22 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0014_remove_member_member_type_member_grand_parent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('duration_months', models.PositiveIntegerField(default=12)),
                ('application_date', models.DateField(auto_now_add=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('collateral', models.TextField(blank=True, null=True)),
                ('collateral_proof', models.FileField(blank=True, null=True, upload_to='collateral_proofs/')),
                ('guarantor', models.CharField(blank=True, max_length=50, null=True)),
                ('purpose', models.CharField(max_length=255)),
                ('penalty_type', models.CharField(choices=[('fixed', 'Fixed Amount'), ('rate', 'Percentage Rate')], default='rate', max_length=5)),
                ('penalty_value', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='pending', max_length=8)),
                ('rejected_reason', models.TextField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='member.member')),
            ],
        ),
    ]
