# Generated by Django 4.2.16 on 2025-05-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='days_to_expiry',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
