# Generated by Django 4.2.16 on 2025-05-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_alter_loan_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='penalty_value',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=9),
        ),
    ]
