# Generated by Django 4.2.16 on 2025-05-22 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_alter_loan_penalty_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='duration_months',
            new_name='tenure',
        ),
    ]
