# Generated by Django 4.2.16 on 2025-05-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0005_rename_duration_months_loan_tenure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='penalty_type',
            field=models.CharField(choices=[('Fixed', 'Fixed Amount'), ('Rate', 'Percentage Rate')], default='Rate', max_length=5),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Paid', 'Paid')], default='Pending', max_length=8),
        ),
    ]
