# Generated by Django 4.2.16 on 2025-05-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0006_alter_loan_penalty_type_alter_loan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='repayment_type',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Yearly', 'Yearly')], default='Monthly', max_length=9),
        ),
    ]
