# Generated by Django 4.2.16 on 2025-05-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0008_alter_loan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='has_penalty',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Disbursed', 'Disbursed'), ('Rejected', 'Rejected'), ('Settled', 'Settled'), ('Cancelled', 'Cancelled')], default='Pending', max_length=9),
        ),
    ]
