# Generated by Django 4.2.16 on 2025-05-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0009_loan_has_penalty_alter_loan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='approved_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
