# Generated by Django 4.2.16 on 2025-05-25 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0010_loan_approved_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='settled_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
