# Generated by Django 4.2.16 on 2025-05-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0012_remove_loan_days_to_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Disbursed', 'Disbursed'), ('Rejected', 'Rejected'), ('Settled', 'Settled'), ('Cancelled', 'Cancelled'), ('Watchlist', 'Watchlist')], default='Pending', max_length=9),
        ),
    ]
