# Generated by Django 4.2.16 on 2025-05-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0013_alter_loan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='penalty_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
