# Generated by Django 4.2.16 on 2025-05-27 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0015_loanrepayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoanRepayment',
        ),
    ]
