# Generated by Django 4.2.16 on 2025-05-28 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0016_delete_loanrepayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='amount',
            new_name='loan_amount',
        ),
    ]
