# Generated by Django 4.2.16 on 2025-05-30 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0017_rename_amount_loan_loan_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_account_number', models.CharField(max_length=20, unique=True)),
                ('accrued_interest', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('interest_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('interest_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_accounts', to='loan.loan')),
            ],
        ),
    ]
