# Generated by Django 4.2.16 on 2025-06-02 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0018_loanaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanaccount',
            name='accrued_interest',
        ),
    ]
