# Generated by Django 4.2.16 on 2025-06-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0019_remove_loanaccount_accrued_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanaccount',
            name='interest_per_day',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
