# Generated by Django 4.2.16 on 2025-06-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0022_loaninterest_interest_amount_loaninterest_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loaninterest',
            name='payment_date',
        ),
        migrations.AlterField(
            model_name='loaninterest',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
