# Generated by Django 4.2.16 on 2024-10-08 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6)),
                ('dob', models.DateField()),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], max_length=7)),
                ('mobile', models.CharField(blank=True, max_length=10)),
                ('address', models.CharField(max_length=50)),
                ('ward', models.CharField(max_length=3)),
                ('house_number', models.CharField(blank=True, max_length=10)),
                ('citizenship_number', models.CharField(blank=True, max_length=10)),
                ('join_date', models.DateField()),
                ('member_type', models.CharField(choices=[('General', 'General'), ('Executive', 'Executive')], default='General', max_length=9)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('citizen_copy', models.ImageField(blank=True, null=True, upload_to='citizen/')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=8)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('member_id', models.CharField(blank=True, max_length=6, unique=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
