# Generated by Django 4.2.16 on 2024-10-08 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_alter_member_dob_alter_member_join_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='dob',
            field=models.DateField(default=datetime.date(2024, 10, 8)),
        ),
        migrations.AlterField(
            model_name='member',
            name='join_date',
            field=models.DateField(blank=True, default=datetime.date(2024, 10, 8), null=True),
        ),
    ]
