# Generated by Django 4.2.16 on 2025-04-04 07:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('member', '0008_alter_member_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('Member', 'Member'), ('Community-Head', 'Community-Head'), ('Executive', 'Executive')], default='Member', max_length=20),
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_name', models.CharField(max_length=255)),
                ('community_head', models.ManyToManyField(related_name='managed_community', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
