# Generated by Django 4.2.16 on 2025-04-06 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_member_role_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.community'),
        ),
    ]
