# Generated by Django 4.2.16 on 2025-04-06 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_member_community'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_members', to='member.community'),
        ),
    ]
