# Generated by Django 4.1.7 on 2025-04-17 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_alter_member_community'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='community_head',
        ),
    ]
