# Generated by Django 4.1.7 on 2025-04-17 07:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('member', '0012_remove_community_community_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='community_head',
            field=models.ManyToManyField(related_name='managed_community', to=settings.AUTH_USER_MODEL),
        ),
    ]
