# Generated by Django 4.2.16 on 2025-05-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0013_community_community_head'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='member_type',
        ),
        migrations.AddField(
            model_name='member',
            name='grand_parent',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='membership_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='parent',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='spouse',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
